"""agrega correo y telefono a usuario, slug y direccion a negocio

Revision ID: 30e82fc01c8c
Revises: 6b8d9c4ee4fc
Create Date: 2026-06-15 19:24:28.180773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30e82fc01c8c'
down_revision: Union[str, Sequence[str], None] = '6b8d9c4ee4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negocio', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('negocio', sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'negocio', ['slug'])
    op.add_column('usuario', sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('usuario', sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('usuario', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('usuario', 'telefono')
    op.drop_column('usuario', 'correo')
    op.drop_constraint(None, 'negocio', type_='unique')
    op.drop_column('negocio', 'direccion')
    op.drop_column('negocio', 'slug')
    # ### end Alembic commands ###
