"""Foreign key faltante

Revision ID: 6b8d9c4ee4fc
Revises: b9ebd4c7f0d3
Create Date: 2026-06-14 20:21:27.259139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8d9c4ee4fc'
down_revision: Union[str, Sequence[str], None] = 'b9ebd4c7f0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
